
#ifndef MatrixBuddy_MATTypes_h
#define MatrixBuddy_MATTypes_h


typedef enum{
  MAT_STATUS_RESULT,
  MAT_STATUS_NORMAL,
  MAT_STATUS_MATRIX_DETERMINANT_ZERO,
  MAT_STATUS_MATRIX_DETERMINANT_ALMOST_ZERO,
  MAT_STATUS_VECTOR_COMPONENT_ZERO,
  MAT_STATUS_VECTOR_COMPONENT_ALMOST_ZERO,
  MAT_STATUS_MATRIX_COMPONENT_ZERO,
  MAT_STATUS_MATRIX_COMPONENT_ALMOST_ZERO,
  MAT_STATUS_SCALAR_ZERO,
  MAT_STATUS_SCALAR_ALMOST_ZERO,
  MAT_STATUS_VECTOR_LENGTH_ZERO,
  MAT_STATUS_VECTOR_LENGTH_ALMOST_ZERO,
  MAT_STATUS_VECTORS_COLINEAR,
  MAT_STATUS_VECTORS_ALMOST_COLINEAR,
  MAT_STATUS_VECTOR_LENGTH_UNEQUAL_ONE,
} MATStatus;


typedef enum{
  MAT_COLOR_NORMAL,
  MAT_COLOR_RESULT,
  MAT_COLOR_ERROR,
  MAT_COLOR_WARNING,
} MATColor;


#define MAT_CODE_STYLE_LEGACY_NONE 0
typedef enum{
  MAT_CODE_STYLE_C_ROW_FIRST_1D = 1,
  MAT_CODE_STYLE_C_ROW_FIRST_2D,
  MAT_CODE_STYLE_C_COLUMN_FIRST_1D,
  MAT_CODE_STYLE_C_COLUMN_FIRST_2D,
  MAT_CODE_STYLE_MATHEMATICA,
  MAT_CODE_STYLE_MATLAB,
  MAT_CODE_STYLE_MAPLE,
} MATCodeStyle;


typedef enum{
  MAT_VALUE_ACCURACY_NATURAL = 0,
  MAT_VALUE_ACCURACY_FLOAT,
} MATValueAccuracy;


typedef enum{
  MAT_COMPUTATION_VMULS,
  MAT_COMPUTATION_VDIVS,
  MAT_COMPUTATION_VMULCOMPV,
  MAT_COMPUTATION_VDIVCOMPV,

  MAT_COMPUTATION_NEGV,
  MAT_COMPUTATION_VADDV,
  MAT_COMPUTATION_VSUBV,
  MAT_COMPUTATION_VDOTV,
  MAT_COMPUTATION_VCROSSV,
  MAT_COMPUTATION_LENGTHV,

  MAT_COMPUTATION_NORMALIZEV,
  MAT_COMPUTATION_ORTHOGONALIZEV,
  MAT_COMPUTATION_MIRRORV,

  MAT_COMPUTATION_MMULS,
  MAT_COMPUTATION_MDIVS,
  MAT_COMPUTATION_MMULCOMPV,
  MAT_COMPUTATION_MDIVCOMPV,
  MAT_COMPUTATION_MMULCOMPM,
  MAT_COMPUTATION_MDIVCOMPM,
  
  MAT_COMPUTATION_MNEG,
  MAT_COMPUTATION_MADDM,
  MAT_COMPUTATION_MSUBM,
  MAT_COMPUTATION_MMULV,
  MAT_COMPUTATION_MMULM,

  MAT_COMPUTATION_DIAGS,
  MAT_COMPUTATION_DIAGV,
  MAT_COMPUTATION_TRANSPOSEM,
  MAT_COMPUTATION_INVERTM,
  
  MAT_COMPUTATION_COUNT
} MATComputation;






#endif // MatrixBuddy_MATTypes_h
