
#ifndef MatrixBuddy_MATTypes_h
#define MatrixBuddy_MATTypes_h


typedef enum{
  MAT_STATUS_RESULT,
  MAT_STATUS_NORMAL,
  MAT_STATUS_MATRIX_DETERMINANT_ZERO,
  MAT_STATUS_MATRIX_DETERMINANT_ALMOST_ZERO,
  MAT_STATUS_VECTOR_COMPONENT_ZERO,
  MAT_STATUS_VECTOR_COMPONENT_ALMOST_ZERO,
  MAT_STATUS_MATRIX_COMPONENT_ZERO,
  MAT_STATUS_MATRIX_COMPONENT_ALMOST_ZERO,
  MAT_STATUS_SCALAR_ZERO,
  MAT_STATUS_SCALAR_ALMOST_ZERO,
  MAT_STATUS_VECTOR_LENGTH_ZERO,
  MAT_STATUS_VECTOR_LENGTH_ALMOST_ZERO,
  MAT_STATUS_VECTORS_COLINEAR,
  MAT_STATUS_VECTORS_ALMOST_COLINEAR,
  MAT_STATUS_VECTOR_LENGTH_UNEQUAL_ONE,
} MATStatus;



typedef enum{
  MAT_COLOR_NORMAL,
  MAT_COLOR_RESULT,
  MAT_COLOR_ERROR,
  MAT_COLOR_WARNING,
} MATColor;



typedef enum{
  MAT_CODE_STYLE_C_ROW_FIRST_1D = 1,
  MAT_CODE_STYLE_C_ROW_FIRST_2D,
  MAT_CODE_STYLE_C_COLUMN_FIRST_1D,
  MAT_CODE_STYLE_C_COLUMN_FIRST_2D,
  MAT_CODE_STYLE_MATHEMATICA,
  MAT_CODE_STYLE_MATLAB,
  MAT_CODE_STYLE_MAPLE,
  MAT_CODE_STYLE_COUNT
} MATCodeStyle;



typedef enum{
  MAT_VALUE_ACCURACY_NATURAL = 0,
  MAT_VALUE_ACCURACY_FLOAT,
  MAT_VALUE_ACCURACY_COUNT
} MATValueAccuracy;



typedef enum{
  MAT_COMPUTATION_VMULS = 0,
  MAT_COMPUTATION_VDIVS,
  MAT_COMPUTATION_VMULCOMPV,
  MAT_COMPUTATION_VDIVCOMPV,

  MAT_COMPUTATION_VNEG,
  MAT_COMPUTATION_VADDV,
  MAT_COMPUTATION_VSUBV,
  MAT_COMPUTATION_VDOTV,
  MAT_COMPUTATION_VCROSSV,
  MAT_COMPUTATION_VLENGTH,

  MAT_COMPUTATION_VNORMALIZE,
  MAT_COMPUTATION_VORTHO,
  MAT_COMPUTATION_VMIRROR,

  MAT_COMPUTATION_MMULS,
  MAT_COMPUTATION_MDIVS,
  MAT_COMPUTATION_MMULCOMPV,
  MAT_COMPUTATION_MDIVCOMPV,
  MAT_COMPUTATION_MMULCOMPM,
  MAT_COMPUTATION_MDIVCOMPM,
  
  MAT_COMPUTATION_MNEG,
  MAT_COMPUTATION_MADDM,
  MAT_COMPUTATION_MSUBM,
  MAT_COMPUTATION_MMULV,
  MAT_COMPUTATION_MMULM,

  MAT_COMPUTATION_MDIAGS,
  MAT_COMPUTATION_MDIAGV,
  MAT_COMPUTATION_MTRANSPOSE,
  MAT_COMPUTATION_MINVERT,
  
  MAT_COMPUTATION_COUNT
} MATComputation;



#endif // MatrixBuddy_MATTypes_h



// This is free and unencumbered software released into the public domain.

// Anyone is free to copy, modify, publish, use, compile, sell, or
// distribute this software, either in source code form or as a compiled
// binary, for any purpose, commercial or non-commercial, and by any
// means.

// In jurisdictions that recognize copyright laws, the author or authors
// of this software dedicate any and all copyright interest in the
// software to the public domain. We make this dedication for the benefit
// of the public at large and to the detriment of our heirs and
// successors. We intend this dedication to be an overt act of
// relinquishment in perpetuity of all present and future rights to this
// software under copyright law.

// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
// OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
// OTHER DEALINGS IN THE SOFTWARE.

// For more information, please refer to <http://unlicense.org/>
